import { sql, type Kysely } from 'kysely';
import type { DB } from '../../db/types.js';

// The unified "Transactions" list (QBO's "Search all transactions"): every
// document type normalized into one row shape, so the page can show them
// together, filter by any of them, and sort/paginate across the mixed set.
//
// Implemented types: deposit, expense, check, journal (standalone manual/
// adjusting only -- entries generated by the other types already appear as
// their own row), bill, payment (AR), credit_memo. Invoices, bill payments,
// and vendor credits aren't included yet; adding one is the same pattern as
// any branch below (business_id-scoped SELECT with the common columns).

export const TRANSACTION_TYPES = ['deposit', 'expense', 'check', 'journal', 'bill', 'payment', 'credit_memo'] as const;
export type TransactionType = (typeof TRANSACTION_TYPES)[number];

export type TransactionRow = {
  id: string;
  type: TransactionType;
  date: string;
  ref_no: string | null;
  contact_id: string | null;
  contact_name: string | null;
  payment_account_name: string | null;
  total_amount: string;
  memo: string | null;
  status: string;
  updated_at: string;
  path: string;
};

export type TransactionSortKey = 'date' | 'type' | 'ref_no' | 'total_amount' | 'updated_at';

export type ListTransactionsQuery = {
  business_id: string;
  type?: TransactionType | null;
  date_start?: string | null;
  date_end?: string | null;
  ref_no?: string | null;
  contact_id?: string | null;
  amount_op?: 'eq' | 'gt' | 'gte' | 'lt' | 'lte' | 'between' | null;
  amount_value?: string | null;
  amount_value2?: string | null;
  sort_key?: TransactionSortKey;
  sort_dir?: 'asc' | 'desc';
  limit: number;
  offset: number;
};

const SORT_COLUMNS: Record<TransactionSortKey, string> = {
  date: 'date',
  type: 'type',
  ref_no: 'ref_no',
  total_amount: 'total_amount',
  updated_at: 'updated_at',
};

// One UNION ALL branch per type, each projecting the same 11 columns. Every
// branch is scoped to business_id directly (cheaper than filtering after the
// union); every other filter (type/date/ref/contact/amount) is applied once,
// outside the union, below.
function unionSql(business_id: string) {
  return sql`
    SELECT 'deposit' AS type, d.id, d.deposit_date AS date, d.deposit_number AS ref_no,
      NULL::uuid AS contact_id, NULL::text AS contact_name,
      ba.name AS payment_account_name, d.total_amount::text AS total_amount, d.memo,
      (CASE WHEN d.voided_at IS NOT NULL THEN 'voided' ELSE 'posted' END) AS status,
      d.updated_at, ('/accounting/bank-deposits/' || d.id) AS path
    FROM bank_deposits d
    JOIN bank_accounts ba ON ba.id = d.bank_account_id
    WHERE d.business_id = ${business_id}

    UNION ALL

    SELECT 'expense', e.id, e.transaction_date, e.reference,
      COALESCE(e.vendor_id, e.customer_id), COALESCE(v.name, c.name, e.payee_text),
      pa.name, e.total_amount::text, e.memo, e.status::text,
      e.updated_at, ('/accounting/expenses/' || e.id)
    FROM expense_transactions e
    LEFT JOIN vendors v ON v.id = e.vendor_id
    LEFT JOIN customers c ON c.id = e.customer_id
    JOIN chart_of_accounts pa ON pa.id = e.payment_account_id
    WHERE e.business_id = ${business_id} AND e.payment_method <> 'check'

    UNION ALL

    SELECT 'check', ch.id, ch.payment_date, ch.check_number,
      ch.payee_id, COALESCE(v2.name, cu2.name, ch.payee_text),
      ba2.name, ch.total_amount::text, ch.memo, ch.status::text,
      ch.updated_at, ('/accounting/checks/' || ch.id)
    FROM checks ch
    LEFT JOIN vendors v2 ON v2.id = ch.payee_id
    LEFT JOIN customers cu2 ON cu2.id = ch.payee_id
    JOIN bank_accounts ba2 ON ba2.id = ch.bank_account_id
    WHERE ch.business_id = ${business_id}

    UNION ALL

    -- Checks written the old way, as an Expense with payment method Check
    -- (see checkService.listChecks -- same reasoning: this cannot become a
    -- real checks-table row without voiding and reposting it).
    SELECT 'check', e2.id, e2.transaction_date, e2.reference,
      e2.vendor_id, COALESCE(v3.name, e2.payee_text),
      COALESCE(ba3.name, pa2.name), e2.total_amount::text, e2.memo, e2.status::text,
      e2.updated_at, ('/accounting/expenses/' || e2.id)
    FROM expense_transactions e2
    LEFT JOIN vendors v3 ON v3.id = e2.vendor_id
    JOIN chart_of_accounts pa2 ON pa2.id = e2.payment_account_id
    LEFT JOIN bank_accounts ba3 ON ba3.cash_account_id = pa2.id
    WHERE e2.business_id = ${business_id} AND e2.payment_method = 'check'

    UNION ALL

    SELECT 'journal', je.id, je.entry_date, je.journal_number,
      NULL::uuid, NULL::text,
      NULL::text, COALESCE((SELECT SUM(jel.debit) FROM journal_entry_lines jel WHERE jel.journal_entry_id = je.id), 0)::text,
      je.memo, je.status::text, je.updated_at, ('/journal/' || je.id)
    FROM journal_entries je
    WHERE je.business_id = ${business_id} AND je.source_type IN ('manual', 'adjustment') AND je.source_id IS NULL

    UNION ALL

    SELECT 'bill', b.id, b.bill_date, b.bill_number,
      b.vendor_id, v4.name,
      NULL::text, b.total::text, b.memo, b.status::text,
      b.updated_at, ('/ap/bills/' || b.id)
    FROM bills b
    JOIN vendors v4 ON v4.id = b.vendor_id
    WHERE b.business_id = ${business_id}

    UNION ALL

    SELECT 'payment', p.id, p.payment_date, p.reference,
      p.customer_id, c2.name,
      coa.name, p.amount::text, p.memo, p.status::text,
      p.updated_at, ('/payments/' || p.id)
    FROM payments p
    JOIN customers c2 ON c2.id = p.customer_id
    JOIN chart_of_accounts coa ON coa.id = p.cash_account_id
    WHERE p.business_id = ${business_id}

    UNION ALL

    SELECT 'credit_memo', cm.id, cm.memo_date, cm.credit_memo_number,
      cm.customer_id, c3.name,
      NULL::text, cm.amount::text, cm.memo, cm.status::text,
      cm.updated_at, ('/credit-memos/' || cm.id)
    FROM credit_memos cm
    JOIN customers c3 ON c3.id = cm.customer_id
    WHERE cm.business_id = ${business_id}
  `;
}

function filteredSql(q: ListTransactionsQuery) {
  const amountValue = q.amount_op && q.amount_op !== 'between' ? q.amount_value ?? null : null;
  const amountLow = q.amount_op === 'between' ? q.amount_value ?? null : null;
  const amountHigh = q.amount_op === 'between' ? q.amount_value2 ?? null : null;
  return sql`
    SELECT * FROM (${unionSql(q.business_id)}) all_tx
    WHERE (${q.type ?? null}::text IS NULL OR type = ${q.type ?? null})
      AND (${q.date_start ?? null}::date IS NULL OR date >= ${q.date_start ?? null}::date)
      AND (${q.date_end ?? null}::date IS NULL OR date <= ${q.date_end ?? null}::date)
      AND (${q.ref_no ?? null}::text IS NULL OR ref_no ILIKE '%' || ${q.ref_no ?? null} || '%')
      AND (${q.contact_id ?? null}::uuid IS NULL OR contact_id = ${q.contact_id ?? null}::uuid)
      AND (${q.amount_op === 'eq' ? amountValue : null}::numeric IS NULL OR total_amount::numeric = ${q.amount_op === 'eq' ? amountValue : null}::numeric)
      AND (${q.amount_op === 'gt' ? amountValue : null}::numeric IS NULL OR total_amount::numeric > ${q.amount_op === 'gt' ? amountValue : null}::numeric)
      AND (${q.amount_op === 'gte' ? amountValue : null}::numeric IS NULL OR total_amount::numeric >= ${q.amount_op === 'gte' ? amountValue : null}::numeric)
      AND (${q.amount_op === 'lt' ? amountValue : null}::numeric IS NULL OR total_amount::numeric < ${q.amount_op === 'lt' ? amountValue : null}::numeric)
      AND (${q.amount_op === 'lte' ? amountValue : null}::numeric IS NULL OR total_amount::numeric <= ${q.amount_op === 'lte' ? amountValue : null}::numeric)
      AND (${amountLow}::numeric IS NULL OR total_amount::numeric >= ${amountLow}::numeric)
      AND (${amountHigh}::numeric IS NULL OR total_amount::numeric <= ${amountHigh}::numeric)
  `;
}

export async function listTransactions(
  db: Kysely<DB>, q: ListTransactionsQuery,
): Promise<{ rows: TransactionRow[]; total: number }> {
  const sortCol = sql.raw(SORT_COLUMNS[q.sort_key ?? 'date']);
  const dir = sql.raw((q.sort_dir ?? 'desc') === 'asc' ? 'ASC' : 'DESC');

  const [rows, countRow] = await Promise.all([
    sql<TransactionRow>`${filteredSql(q)} ORDER BY ${sortCol} ${dir}, date DESC LIMIT ${q.limit} OFFSET ${q.offset}`
      .execute(db),
    sql<{ count: string }>`SELECT COUNT(*) AS count FROM (${filteredSql(q)}) counted`.execute(db),
  ]);

  return { rows: rows.rows, total: Number(countRow.rows[0]?.count ?? 0) };
}
