export const ERR = {
  // Input
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',

  // Resource
  NOT_FOUND: 'NOT_FOUND',

  // Business rules (used by 1.1 and 1.2 as well)
  CLOSED_PERIOD: 'CLOSED_PERIOD',
  UNBALANCED_ENTRY: 'UNBALANCED_ENTRY',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  IMMUTABLE_RECORD: 'IMMUTABLE_RECORD',
  OVERAPPLICATION: 'OVERAPPLICATION',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  PRECONDITION_FAILED: 'PRECONDITION_FAILED',

  // Fallback
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ERR)[keyof typeof ERR];
