// apps/api/src/app.ts
import express, { type Express } from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import { corsOrigins } from './config.js';
import { requestId } from './middleware/requestId.js';
import { errorHandler } from './middleware/error.js';
import authRoutes from './routes/auth.js';
import meRoutes from './routes/me.js';
import healthRoutes from './routes/health.js';
import coaRoutes from './routes/chartOfAccounts.js';
import periodRoutes from './routes/fiscalPeriods.js';
import journalEntryRoutes from './routes/journalEntries.js';
import trialBalanceRoutes from './routes/trialBalance.js';
import customerRoutes from './routes/customers.js';
import taxCodeRoutes from './routes/taxCodes.js';
import invoiceRoutes from './routes/invoices.js';
import paymentRoutes from './routes/payments.js';
import creditMemoRoutes from './routes/creditMemos.js';
import agingReportRoutes from './routes/agingReport.js';
import financialReportRoutes from './routes/financialReports.js';
import vendorRoutes from './routes/vendors.js';
import billRoutes from './routes/bills.js';
import billPaymentRoutes from './routes/billPayments.js';
import vendorCreditRoutes from './routes/vendorCredits.js';
import tenNinetyNineReportRoutes from './routes/tenNinetyNineReport.js';
import bankAccountRoutes from './routes/bankAccounts.js';
import bankTransactionRoutes from './routes/bankTransactions.js';
import reconciliationRoutes from './routes/reconciliations.js';
import bankRuleRoutes from './routes/bankRules.js';
import fixedAssetRoutes from './routes/fixedAssets.js';
import businessesRoutes from './routes/businesses.js';
import usersRoutes from './routes/users.js';
import costCentersRoutes from './routes/costCenters.js';
import inventoryItemsRoutes from './routes/inventoryItems.js';
import expenseTransactionsRouter from './routes/expenseTransactions.js';
import apOverviewRouter from './routes/apOverview.js';
import firmOverviewRouter from './routes/firmOverview.js';
import periodReviewRouter from './routes/periodReview.js';
import recurringTemplatesRouter from './routes/recurringTemplates.js';
import filesRouter from './routes/files.js';
import receiptsRouter from './routes/receipts.js';
import integrationInboxRouter from './routes/integrationInbox.js';

export function makeApp(): Express {
  const app = express();
  app.use(requestId);
  app.use(cors({
    origin: (origin, cb) => {
      if (!origin) return cb(null, true);
      if (corsOrigins.includes(origin)) return cb(null, true);
      cb(new Error(`CORS: origin ${origin} not allowed`));
    },
    credentials: true,
  }));
  app.use(cookieParser());
  app.use(express.json({ limit: '1mb' }));
  app.use(healthRoutes);
  app.use(authRoutes);
  app.use(meRoutes);
  app.use(coaRoutes);
  app.use(periodRoutes);
  app.use(journalEntryRoutes);
  app.use(trialBalanceRoutes);
  app.use(customerRoutes);
  app.use(taxCodeRoutes);
  app.use(invoiceRoutes);
  app.use(paymentRoutes);
  app.use(creditMemoRoutes);
  app.use(agingReportRoutes);
  app.use(financialReportRoutes);
  app.use(vendorRoutes);
  app.use(billRoutes);
  app.use(billPaymentRoutes);
  app.use(vendorCreditRoutes);
  app.use(tenNinetyNineReportRoutes);
  app.use(bankAccountRoutes);
  app.use(bankTransactionRoutes);
  app.use(reconciliationRoutes);
  app.use(bankRuleRoutes);
  app.use(fixedAssetRoutes);
  app.use(businessesRoutes);
  app.use(usersRoutes);
  app.use(costCentersRoutes);
  app.use(inventoryItemsRoutes);
  app.use(expenseTransactionsRouter);
  app.use(apOverviewRouter);
  app.use(firmOverviewRouter);
  app.use(periodReviewRouter);
  app.use(recurringTemplatesRouter);
  app.use(filesRouter);
  app.use(receiptsRouter);
  app.use(integrationInboxRouter);
  app.use(errorHandler);
  return app;
}
